#!/usr/bin/env osascript

# Installation:
# sudo ln -s $PWD/ssh-askpass /usr/libexec/ssh-askpass
# chmod +x /usr/libexec/ssh-askpass

on run argv
    set args to argv as text
    set frontmost_application to name of (info for (path to frontmost application))
    tell application frontmost_application
        display dialog args with icon caution
        if result = {button returned:"OK"} then
            return
        end if
        return false
    end tell
end run
